### ISSUE TITLE
Bulk Delete Taxonomy terms

### ISSUE THREAD

**Issue by shefik** [sudar/bulk-delete#116]
Please add the ability to bulk delete taxonomy terms for custom post types, as well as regular post types.

**Comment by sudar** [comment]
Based on what criteria do you want to delete these terms?

**Comment by sudar** [comment]
This will be done together with #19 and #46

**Comment by sudar** [comment]
This will be done as part of #178

**Comment by sudar** [comment]
This feature is now merged and will be released as part of v6.0.0
