### ISSUE TITLE
Show update notice even if license is not valid

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#119]

**Comment by mariadanieldeepak** [comment]
@sudar,

Currently there is a notice shown to user when license is not valid. Are you mentioning a different notice altogether?

![image](https://user-images.githubusercontent.com/17510033/31421182-8c7cbfbe-ae63-11e7-836b-e652b5e5245c.png)

**Comment by sudar** [comment]
The above message is shown to users if they have not entered the license key.

What I am asking in this issue is to show the 'update' notification in the plugins list page, when there is an update to add-on available even if the license is not valid.

**Comment by sudar** [comment]
On second thought, I think I will take this up, since I have already did this for Email Log.
