### ISSUE TITLE
Deleting private posts resulted deletion of published posts

### ISSUE THREAD

**Issue by dx486** [sudar/bulk-delete#127]
Deleting private posts resulted deletion of published posts as well. I tried it twice with same result.

Wordpress version: 4.7.2
Bulk delete version: 5.5.5

**Comment by sudar** [comment]
That's really bad. Not sure if anything changed in WordPress recently regarding private posts.

I will check it and get back.

**Comment by mariadanieldeepak** [comment]
@sudar,

I'm not able to replicate the issue reported. The following are the steps I performed along with my observations.

**Step 01: Setting up the stage.**

I've created private and published posts in a clean WP install.

![image](https://user-images.githubusercontent.com/17510033/31811516-75613b3e-b59d-11e7-852b-b49dc08db11f.png)

**Step 02: Installed Bulk Delete Plugin from Github**

![image](https://user-images.githubusercontent.com/17510033/31811520-7adb3bf0-b59d-11e7-9686-d77569b246b4.png)

**Step 03: Deleting posts by post status**

![image](https://user-images.githubusercontent.com/17510033/31811526-848c1ec6-b59d-11e7-81bb-09a40c10a041.png)

**Step 04: The Bulk Delete action deletes only Published posts and not private posts**

![image](https://user-images.githubusercontent.com/17510033/31811559-97a5cb2e-b59d-11e7-87f8-b787fbfd0007.png)

**Step 05: Private posts remain after deleting published posts**

![image](https://user-images.githubusercontent.com/17510033/31811564-9a4b4476-b59d-11e7-8b85-bdb8f96f71b3.png)

Finally, I also repeated the same steps with the plugin downloaded from WP plugin repository. And the results were the same.

![image](https://user-images.githubusercontent.com/17510033/31812015-4166e7e6-b59f-11e7-9cca-4b288805ce7b.png)

If there are any recordings or screenshots explaining/re-producing the issue, then it would be greatly appreciated and would help to resolve the issue.

**Comment by sudar** [comment]
@dx486 

First of all apologies for delay in getting back to you.

Finally we got around this issue, but we are not able to replicate it. @mariadanieldeepak from the Bulk WP team tried to replicate it and have noted the steps that he followed above.

Are you still facing this issue? If yes, then can you please let us know the exact steps that you did to replicate it? Thanks.

**Comment by sudar** [comment]
@dx486 

Can you please let us know whether you are still facing this issue?

**Comment by dx486** [comment]
Hello sudar,
Sorry for not seeing your message before.
I don't have a testing environment for this right now. So if you cannot replicate it, it's OK for me that you mark this issue as resolved. If I will face it again, I will let you know.

**Comment by sudar** [comment]
Hello @dx486 

Thanks for the reply.

I will close this issue for now, but if you ever face this issue again, please let me know.
