### ISSUE TITLE
Remove iframes

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#132]

**Comment by mariadanieldeepak** [comment]
@sudar,

I've removed the iFrames sidebar from all of the admin pages.

However, I'm not quite sure, where the following method is used exactly.

https://github.com/sudar/bulk-delete/blob/master/include/settings/class-bd-settings-page.php#L100

So I didn't delete the following method.

https://github.com/sudar/bulk-delete/blob/master/include/ui/form.php#L181-L192

Kindly review the changes and let me know if there's anything to be done.

**Comment by sudar** [comment]
@mariadanieldeepak 

You can remove that method. Just make sure you have removed all references to it.

**Comment by mariadanieldeepak** [comment]
> You can remove that method. Just make sure you have removed all references to it.

Removed.
