### ISSUE TITLE
Delete users who don't have orders in Easy Digital Downloads

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#134]
Can be done together with #130

**Comment by mariadanieldeepak** [comment]
@sudar,

How do we identify the Users with no EDD orders? I would like to know if we must use EDD API to do so or just by running a SQL query? 

![image](https://user-images.githubusercontent.com/17510033/33867781-f5202bf4-df24-11e7-8538-9ec48c944133.png)
 
When using SQL query, a LEFT JOIN between `wp_users` and `wp_edd_customers` on **User ID** where wp_edd_customers.user_id is NULL will return the list of users with no orders. Should we delete all the users in that list? The reason I ask the question is that the list may contain Admin users if they have no Orders.

**Comment by mariadanieldeepak** [comment]
@sudar,

Filter no.:3 doesn't make sense to this to-do. So I'm skipping it and holding the rest.

![image](https://user-images.githubusercontent.com/17510033/33975865-7225249a-e0b7-11e7-9721-d508f9c72e5a.png)
 
Kindly let me know your thoughts.

**Comment by sudar** [comment]
Yeah you can remove filter 3.

I will let you know if there is an api available with EDD.

**Comment by sudar** [comment]
@mariadanieldeepak 

Let's move the discussion to the add-on repo.

**Comment by sudar** [comment]
Add-on in development.

**Comment by wsenjer** [comment]
Hello, is this addon implemented?
