### ISSUE TITLE
Construct post modules using the classes like user modules

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#137]

**Comment by mariadanieldeepak** [comment]
**Impact Analysis**:

When `Bulk_Delete_Posts` class is changed/removed, the following add-ons will be affected.

- https://github.com/sudar/bulk-delete-scheduler-for-deleting-posts-by-taxonomy
- https://github.com/sudar/bulk-delete-scheduler-for-deleting-posts-by-status
- https://github.com/sudar/bulk-delete-scheduler-for-deleting-posts-by-post-type
- https://github.com/sudar/bulk-delete-scheduler-for-deleting-posts-by-category
- https://github.com/sudar/bulk-delete-scheduler-for-deleting-posts-by-tag

The remaining add-ons use methods within the add-on class to delete posts.

- https://github.com/sudar/bulk-delete-from-trash
- https://github.com/sudar/bulk-delete-posts-by-content

- https://github.com/sudar/bulk-delete-posts-by-custom-field
- https://github.com/sudar/bulk-delete-posts-by-duplicate-title
- https://github.com/sudar/bulk-delete-posts-by-title
- https://github.com/sudar/bulk-delete-posts-by-user-role
- https://github.com/sudar/bulk-delete-posts-by-word-count
- https://github.com/sudar/bulk-delete-scheduler-for-deleting-posts-by-custom-field
- https://github.com/sudar/bulk-delete-scheduler-for-deleting-posts-by-duplicate-title
- https://github.com/sudar/bulk-delete-scheduler-for-deleting-posts-by-title
- https://github.com/sudar/bulk-delete-scheduler-for-deleting-posts-by-user-role

**Comment by sudar** [comment]
@mariadanieldeepak 

Great job doing the impact analysis and also for sending me the screencast of your design proposal.

I have a slightly different idea of implementing it. Let's talk it over a call.

Also we need to maintain backward compatibility with the add-ons.
