### ISSUE TITLE
Bulk Delete Comments

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#146]
- [x] Create a new page called `Bulk Delete Comments`
- [x] Create `Delete Comments by Author` module. Should support deleting by author name, email or url.
- [x] Create `Delete Comments by IP Address` module

The schedulers will be part of [Scheduler for Deleting Comments](https://github.com/sudar/scheduler-for-deleting-comments/) add-on

**Comment by esudalaimadan** [comment]
@sudar 

**Pending items:**

1. WP_Comment_Query does not support comment author name.
2. WP_Comment_Query does not support comment author IP.

Please let me know whether we have to use custom query for the above cases.

**Comment by sudar** [comment]
@esudalaimadan 

I have added the Query Overrider. You can use the following code.

```php
$args['bd_db_column_name'] = 'comment_author_IP';
$args['bd_db_column_value'] = '127.0.0.1';
$query_overrider = new DeleteCommentsQueryOverrider();
$query_overrider->load();
```
