### ISSUE TITLE
Delete Users by User Role - Delete Buddypress 'pending' users

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#151]
'pending' users are described here - https://buddypress.org/support/topic/how-to-mass-delete-pending-users-1-million-users-i-already-did-phpmyadmin/#post-231732

Request came through support forum

**Comment by sudar** [comment]
@esudalaimadan 

Since you have BuddyPress installed, checkout what needs to be done for this.

**Comment by esudalaimadan** [comment]
BuddyPress pending users can be deleted using DeleteUsersByUserMeta module by selecting following meta:
**meta key:** _bprwg_is_moderated
**meta_value:** true

**Comment by esudalaimadan** [comment]
With BuddyPress activation, single and multisites are behaving differently.
**Multisite:**
Pending users do not have entries in wp_users table.  They are only in wp_signups table. We can not delete pending users as they are not available in wp_users table.
**Singlesite:**
Pending users have entries in wp_users and wp_signups tables. So we can delete them using Delete Users By User Meta module (meta key and meta value to be used are specified in the above comment).

**Comment by sudar** [comment]
Let's create a new module to delete pending users from BuddyPress.

This module should check if BuddyPress is installed. If not, it will just display a message to the user.
