### ISSUE TITLE
Delete Posts By Word Count addon: Add Post Status filter

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#152]
Addon: https://github.com/sudar/bulk-delete-posts-by-word-count/

This issue was identified as part of [another](https://github.com/sudar/bulk-delete/issues/20#issuecomment-346920601) issue.

Goal: Add a post status filter next to the Post type.

**Comment by sudar** [comment]
Moved this to the add-on repo.
