### ISSUE TITLE
Construct misc modules using the classes like user modules

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#163]
- [ ] Refactor `Bulk Delete Misc` page
- [ ] Refactor `Delete Jetpack Contact Form Messages` module
- [ ] Write just a few tests. No need to be through

**Comment by esudalaimadan** [comment]
On hold as per discussion with @sudar .

**Comment by sudar** [comment]
Closing this as `won'tfix` since setting up Jetpack locally is having some issues and we are not going to get any benefit in porting this over.
