### ISSUE TITLE
Suggestion: Bulk Delete By Category metabox (User experience)

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#165]
Problem: The public posts and private posts in the filtering options are slightly confusing. Users may/might not know the difference between the two.

Solution: The solution is use to describe what each option does, may be using a tool tip or even using toggle `<div>`.

![image](https://user-images.githubusercontent.com/17510033/34284550-dabd98ec-e6f8-11e7-9fa7-3121415919c9.png)

BTW, the "Select Categories" looks cool!

**Comment by sudar** [comment]
@mariadanieldeepak 

Did you check #161 that I created yesterday :)
