### ISSUE TITLE
Request: Core needs to be modified

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#174]
Include additional option [here](https://github.com/sudar/bulk-delete/blob/master/include/meta/class-bulk-delete-post-meta.php#L94)

The option should be called as "Delete based on post meta key name prefix & suffix"

**Example**

![image](https://user-images.githubusercontent.com/17510033/34460352-a5f6f2d0-ee31-11e7-9994-35c37cdf37d7.png)

The above changes are required as part of sudar/bulk-delete-post-meta#1

**Comment by sudar** [comment]
@mariadanieldeepak 

Go ahead and send me a pull request. But branch off from master since we might have to make a point release to Bulk Delete instead of waiting for 5.7.0 release
