### ISSUE TITLE
Delete Taxonomy Terms - Based on post count

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#177]
- [x] Create a new module with the name 'Delete Taxonomy Terms by post count' in the Delete Terms page.
- [x] Choose the taxonomy. Single select dropdown. Create Helper functions in `Renderer`.
- [x] Choose the post type. Single select dropdown.
- [x] A dropdown to choose the operation. Possible values (not equal to, equal to, less than, greater than)
- [x] A textbox to enter the post count.

**Comment by rajanit2000** [comment]
Could not pass `post type` in taxonomy query, and could not get post counts for selected post counts

**Comment by sudar** [comment]
This is done as part of #332

**Comment by rajanit2000** [comment]
Status: #332

**Comment by mariadanieldeepak** [comment]
@rajanit2000,

There is a blocker.

**Screenshot**: Data setup

![image](https://user-images.githubusercontent.com/17510033/43501127-a6ad4d04-9571-11e8-9524-3d215149a764.png)

**Screenshot**: Deletion criteria

![image](https://user-images.githubusercontent.com/17510033/43501148-c172ccf4-9571-11e8-86b0-900c92a7143d.png)

**Screenshot**: Output

The expected result is 1, but looking at the screenshot it is clear that the module isn't deleting terms.

![image](https://user-images.githubusercontent.com/17510033/43501159-cbcfa7da-9571-11e8-948f-be150dddef68.png)
 
When you fix this issue, I would like you to test all the scenarios in the module. For each scenario, I would like to see the following

[ ] Take screenshot of the data setup
[ ] Take a screenshot of the module setup
[ ] Take a screenshot of the Output
[ ] Take a screenshot of the WP CLI output

Please be shrewd and do a self review before sending it to the actual review.

**Comment by mariadanieldeepak** [comment]
@rajanit2000

Did you get a chance to see the above comment?
