### ISSUE TITLE
Delete Taxonomy Terms - Based on postfix and prefix

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#178]
- [x] Create a new Delete Terms page.
- [x] Ability to choose a taxonomy
- [x] Ability to choose terms. Use the following format Delete terms that |select| with |textbox| (equal to, not equal to, starts with, ends with, contains, non contains)
- [ ] Filter: Only if it doesn't contain any post
- [x] Change name to 'Delete Taxonomy Terms by Name'

**Comment by rajanit2000** [comment]
1. Could not filter terms by  not equal to, starts with, ends with and non-contains options
2. Could not filter by Only if it doesn't contain any post

**Comment by mariadanieldeepak** [comment]
@rajanit2000,

Glad that we are unblocked on this now.

Kindly check-in the changes made and verify that the other test cases run as expected. Finally, after a self-review, assign the issue to @sudar for further review.

**Comment by mariadanieldeepak** [comment]
@rajanit2000,

The following WPSE answer should help you progress this issue.
https://wordpress.stackexchange.com/a/178518/83739

Let us know if you're able to make some progress.

**Comment by mariadanieldeepak** [comment]
@rajanit2000,

To debug your SQL query, you can set BD_DEBUG to `true` in your `wp-config` file.

Check this out - 

https://github.com/sudar/bulk-delete/blob/821cd72efb0e5d9fff563431a10dbf73671feb55/include/Core/Controller.php#L36

**Comment by rajanit2000** [comment]
Status: #332

**Comment by rajanit2000** [comment]
@sudar Its done and ready to review.

**Comment by sudar** [comment]
@rajanit2000 

Left some more review comments for you.

**Comment by mariadanieldeepak** [comment]
@rajanit2000, @sudar,

> Filter: Only if it doesn't contain any post 

Is there a reason to ignore this from the check-lists in the description?

**Comment by mariadanieldeepak** [comment]
@rajanit2000, @sudar,

The following are the UI/UX feedbacks that have to be fixed.

- [ ] https://github.com/sudar/bulk-delete/pull/332#issuecomment-407274122
- [ ] https://github.com/sudar/bulk-delete/pull/332#issuecomment-407274462
- [ ] https://github.com/sudar/bulk-delete/pull/332#issuecomment-407274680
- [ ] https://github.com/sudar/bulk-delete/pull/332#issuecomment-407275192
- [ ] https://github.com/sudar/bulk-delete/pull/332#issuecomment-407275470
- [ ] https://github.com/sudar/bulk-delete/pull/332#issuecomment-407275743
- [ ] https://github.com/sudar/bulk-delete/pull/332#issuecomment-407276163

**Comment by mariadanieldeepak** [comment]
@rajanit2000,

I'm afraid that the code isn't doing the expected.

![image](https://user-images.githubusercontent.com/17510033/43117381-22d924dc-8f2a-11e8-979a-e77ec80aea5a.png)

The following should delete only two tags from the above setup. But looking at the result above, it deleted all three.

![image](https://user-images.githubusercontent.com/17510033/43117394-2e67fc60-8f2a-11e8-8c30-7680276d1eb7.png)

**Comment by mariadanieldeepak** [comment]
@rajanit2000 What's your deletion criteria? I couldn't see any information on that.

**Comment by rajanit2000** [comment]
![image](https://user-images.githubusercontent.com/2988033/43438824-d8f468ca-94ad-11e8-9e06-7697bcac121c.png)

![image](https://user-images.githubusercontent.com/2988033/43438844-e578b7ae-94ad-11e8-995b-7799698408ac.png)

@mariadanieldeepak this issue fixed

**Comment by mariadanieldeepak** [comment]
@rajanit2000,

Looking at your deletion criteria [above](https://github.com/sudar/bulk-delete/issues/178#issuecomment-409097124), no tags should be deleted. Could you please retest and let us know?

**Comment by rajanit2000** [comment]
@mariadanieldeepak Sorry above screenshot is taken by mistake

Here new one, Its working fine 

![image](https://user-images.githubusercontent.com/2988033/43547237-4b24e19a-95f8-11e8-88e8-e298884cf4ab.png)

![image](https://user-images.githubusercontent.com/2988033/43547251-55ca66ce-95f8-11e8-973d-bd93e2d20ca2.png)
