### ISSUE TITLE
Suggestion: Delete multiple CPT's or Taxonomies at once

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#180]
This is a requested feature [here](https://wordpress.org/support/topic/feature-requests-103/#post-6981211).

**Comment by sudar** [comment]
@mariadanieldeepak 

Are you referring to deleting posts in CPT or taxonomy or the actual CPT itself?

**Comment by mariadanieldeepak** [comment]
@sudar,

I referred the CPT itself. Additionally the custom taxonomies. Assume, both the CPT and the custom taxonomy are created by CPT UI plugin. In that case, a CPT UI user who chooses delete the registered CPT, would require this.

**Comment by sudar** [comment]
Closing this since it is a very very niche request.

We can look at it again if there are significant requests.
