### ISSUE TITLE
small typo in plugin

### ISSUE THREAD

**Issue by nitinthewiz** [sudar/bulk-delete#181]
Hey!

I noticed that there's a small typo in the plugin -

Where ever it says - 

"Use this option if there are more than 1000 posts and the script timesout."

It should instead be - 

"Use this option if there are more than 1000 posts and the script times out."

If you want, I can send a pull request with this change but otherwise, can you please add the space between 'times' and 'out'?

Thanks for this amazing plugin!

**Comment by sudar** [comment]
@nitinthewiz 

Nice to know that you like the plugin and thanks for reporting the typo.

We will handle it as part of next release.

> If you want, I can send a pull request with this change but otherwise, can you please add the space between 'times' and 'out'?

If you are interested and have time then please do send a PR. If not, no worries :)

**Comment by sudar** [comment]
@nitinthewiz 

The typos are fixed.

The fixes will be released in v5.6.1 in a couple of days.

**Comment by nitinthewiz** [comment]
Thanks! So sorry I couldn't get around to sending a PR! 😄

**Comment by sudar** [comment]
@nitinthewiz 

Not a problem at all :)

We have released v5.6.1 with the above fix.
