### ISSUE TITLE
Plugin page crashes if there are huge number of tags or categories

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#194]
We should not try to load all the tags/categories.

Requested at https://bulkwp.com/support/topic/bulk-delete-posts-page-timeout/

**Comment by sudar** [comment]
@rajanit2000 

If you go to Bulk WP -> Bulk Delete Posts page, all the categories are listed in the 'By category' module and all the tags are listed in the 'By Tag' module.

Both these modules will fail if there are huge number of tags or categories in a WordPress install.

Right now we are using select2 library to make the dropdown pretty, but still all the categories/tags are loaded when the page is loaded.

The select2 library has a way by which we can dynamically load the values in the dropdown as the user types using AJAX - https://select2.org/data-sources/ajax

Refactor the dropdowns to use AJAX if there are more than 50 entities.

**Comment by rajanit2000** [comment]
@sudar 

![image](https://user-images.githubusercontent.com/2988033/36275701-8b2e55a2-12b1-11e8-9b83-02e09bc43dae.png)

CSS and JS file path is miss-match between wp repo plugin and 5.7.0 

May i know the reason?

**Comment by sudar** [comment]
@rajanit2000 

This is because you have not setup the dev tools.

Check the `Setting up source repos` section in the engineering workflow document.
