### ISSUE TITLE
Bulk delete posts based on word count

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#20]

**Comment by mariadanieldeepak** [comment]
@sudar,

Is this implementation going to be an add-on?

**Comment by sudar** [comment]
This will be done as a new add-on similar to http://bulkwp.com/addons/bulk-delete-posts-by-content/

Users will be able to choose custom post types and then whether title has to be checked or content has to be checked.

Next they can specify a word count and then can choose whether it has to be less than that or greater than that.

**Comment by mariadanieldeepak** [comment]
@sudar,

Please create a repo for this add-on and invite me as collaborator.

**Comment by sudar** [comment]
I just checked and found that I had already created the repo and have added you.

The repo is available at https://github.com/sudar/bulk-delete-posts-by-word-count

**Comment by sudar** [comment]
@mariadanieldeepak 

Also add an option to delete posts that are empty.

**Comment by mariadanieldeepak** [comment]
@Sudar,

The following are the screenshots of UI of the Bulk Delete Posts by Word Count add-on.

![image](https://user-images.githubusercontent.com/17510033/33002469-6d8d62d4-cdda-11e7-9939-3a78b8fdf9ba.png)

**Screenshots:** The following screenshots are same as the above one, but with the dropdown options expanded.

![image](https://user-images.githubusercontent.com/17510033/33002443-4abbbf3a-cdda-11e7-8938-669620f23755.png)

![image](https://user-images.githubusercontent.com/17510033/33002446-50765926-cdda-11e7-8f4d-d8e52d621389.png)

Kindly take a look at the screenshots and let me know if there are any options missing. I've provided all the options that I understood from the issue description.

**Comment by sudar** [comment]
@mariadanieldeepak 

Looks good. All options make sense.

**Comment by mariadanieldeepak** [comment]
@Sudar,

I, actually, feel that post status is missing in the above section. That will give more granular control for the Users. I would like to get your feedback on that.

**Comment by sudar** [comment]
@mariadanieldeepak 

Add it to the backlog. Let's get it out without post status for now.

Eventually we will make post status as a filter and include it in all modules.

**Comment by mariadanieldeepak** [comment]
@Sudar,

The [issue](https://github.com/sudar/bulk-delete/issues/152) has been added to GH.

**Comment by sudar** [comment]
Closing this issue, and the progress will be tracked in the add-on repo.

**Comment by Mazup** [comment]
Cant find this option in free version. :-(
