### ISSUE TITLE
Stick to DRY by using the helper function

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#204]
Replace the following lines with the [helper](https://github.com/sudar/bulk-delete/blob/dev/6.0.0/include/ui/form.php#L227) function and ensure the flow works without issues.

https://github.com/sudar/bulk-delete/blob/dev/6.0.0/include/posts/class-bulk-delete-posts.php#L26-L60

**Comment by sudar** [comment]
This will be done as part of #137

**Comment by sudar** [comment]
Closing this since the code has already been refactored.
