### ISSUE TITLE
Ability to delete attachments of posts that are getting deleted

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#205]
Requested at https://wordpress.org/support/topic/delete-post-attachments-too/

**Comment by Zerquix18** [comment]
Hi. I want this feature to be implemented. Are you working on this or accepting any contributions (via code)?
Thanks

**Comment by sudar** [comment]
Hello @Zerquix18 

We have queued up this feature for `v6.1.0` release. We are currently at feature freeze for `v6.0.0` release which will be released in a couple of days.

We are open to all types of contributions (code, documentation, help with QA etc) :)

The only requirement is that you should agree to license your contributions using GPL License (the license this plugins uses which is also the requirement for creating WordPress plugins)
