### ISSUE TITLE
Add feature - bulk delete followers

### ISSUE THREAD

**Issue by Rogrmail** [sudar/bulk-delete#248]
I get a lot of spam FOLLOWERS (subscribers via Jetpack).  I want to delete them but deleting 500 or so one by one on Wordpress.org is impossible.

**Comment by sudar** [comment]
@Rogrmail 

Thanks for logging the feature request.

Are you deleting the spam Followers from your WordPress install or from WordPress.com interface?

Also please post a screenshot of the page where you are deleting the followers. Thanks.

**Comment by Rogrmail** [comment]
It seems impossible to delete followers from my WordPress install (http://beniciaindependent.com/).  I can delete followers one at a time on my WordPress.com interface, 2 screenshots below.
![wp_delete-followers_beniciaindependent](https://user-images.githubusercontent.com/38168259/38470254-f9bb77da-3b14-11e8-9eca-45df58ee8874.jpg)
![wp_delete-email-followers_beniciaindependent](https://user-images.githubusercontent.com/38168259/38470281-4ced6364-3b15-11e8-9a4d-330dcba724af.jpg)

**Comment by Rogrmail** [comment]
Here are screenshots from my Wordpress install - unable to delete anything from here.  
![image](https://user-images.githubusercontent.com/38168259/38470317-c568255e-3b15-11e8-848a-82063c3ad2a6.png)
![image](https://user-images.githubusercontent.com/38168259/38470321-cc5438c6-3b15-11e8-8177-53d2772f2927.png)
![image](https://user-images.githubusercontent.com/38168259/38470324-d3e622ca-3b15-11e8-8a24-168d80ea82b5.png)

**Comment by sudar** [comment]
@Rogrmail 

Yeah that's what I thought. The Jetpack plugin doesn't provide a way to delete subscribers from your WordPress install.

Since the Jetpack plugin doesn't provide a way to delete users, I am not sure if there is a way for us to add the bulk delete ability.

**Comment by Rogrmail** [comment]
Where does Jetpack keep its files??

**Comment by sudar** [comment]
@Rogrmail 

Jetpack keeps all the data about subscribers in their WordPress.com servers and not in the WordPress install database.

**Comment by Rogrmail** [comment]
Thanks, Sudar - So do you mean that Jetpack keeps the data on the servers holding my Wordpress installation?  Or is the data on Jetpack's servers somewhere that I can't access?  If it's on my GoDaddy shared server, maybe I can find the file using FTP, and open and edit it somehow.  
Sorry for all my amateur questions - you've been great giving this issue your attention!

**Comment by sudar** [comment]
Jetpack keeps the data on their own servers, not in the servers holding your WordPress installation that is hosted in GoDaddy.

**Comment by Rogrmail** [comment]
Thanks for your good info.  Sorry there's no solution to this.  I've also searched JetPack help - nothing available on this there.  Good bye, take care and thanks again!

**Comment by sudar** [comment]
@Rogrmail 

Not a problem and thanks for bringing it up.

I wish we had a solution for your problem :(

Closing this for now, since nothing can be done from our plugin's perspective to solve this problem.
