### ISSUE TITLE
Move helper methods from BaseModule into seperate classes

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#253]
- [ ] Move all fetch related methods to Fetcher. Anything that starts with `get_`
- [ ] Move all render related functions to Renderer. Anything that starts with a `render_`

@esudalaimadan 

Before actually moving the methods, give me the list of methods that you are going to move, so that I can quickly review it before the actual code change.

**Comment by esudalaimadan** [comment]
Fetcher functions:-
get_hidden_box_user_meta_field
get_cron_hook
get_field_slug
get_action
get_task_list_link
get_enhanced_select_threshold
get_cron_label

Render functions:-
render_box
render_filtering_table_header
render_restrict_settings
render_delete_settings
render_sticky_settings
render_limit_settings
render_cron_settings
render_submit_button

@sudar Please Let me know the list of functions to be moved.

**Comment by sudar** [comment]
@esudalaimadan 

Move the following functions.

## To Fetcher

- [ ] get_sticky_posts  from PostModule
- [ ] get_categories from PostModule
- [ ] are_tags_present from PostModule
- [ ] are_sticky_post_present from PostModule
- [ ] get_tags  from PostModule

## To Renderer
- [ ] get_enhanced_select_threshold from BaseModule (This function is related to Renderer not Fetcher)
- [ ] render_category_dropdown from PostModule
- [ ] render_tags_dropdown from PostModule
- [ ] render_sticky_post_dropdown from PostModule
- [ ] render_post_type_checkboxes from UserModule
