### ISSUE TITLE
Show/Hide metabox is not working

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#27]
Seems to have been broken by this commit fcc71e2905a0dbc68059d1d52ebe63d16f9c08ab

**Comment by sudar** [comment]
@mariadanieldeepak 

I am very curious why wafflebot assigned this ticket to you.

**Comment by mariadanieldeepak** [comment]
@sudar,

While testing the WaffleBot during WIKI creating, I created a branch in `bulk-delete` repo rather than `bulk-move`. I believe that was the reason why Wafflebot assigned the ticket to me.

**Comment by sudar** [comment]
Okay. Then waffle bot was working.

I was wondering whether there were any bugs in waffle. That's why I asked you.
