### ISSUE TITLE
Ran into `npm audit` warning

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#339]
@sudar,

I ran in to this warning when I pulled the latest from the repo and did an `npm install`. Could you please advise if this is something that should be taken care of?

![image](https://user-images.githubusercontent.com/17510033/41815518-3721cde2-778b-11e8-85b8-c738cd8ca2bd.png)

**Comment by mariadanieldeepak** [comment]
@sudar,

I still get the warning, and here is a [screencast](https://bulkwp.slack.com/files/U113477N1/FBEMQ6CE6/npm_install_security_audity_error.mp4) on the same.

**Comment by sudar** [comment]
@mariadanieldeepak 

Can you post your npm and node versions?

Also I am assuming you are using the latest `dev/6.0.0` branch

**Comment by mariadanieldeepak** [comment]
@sudar,

![image](https://user-images.githubusercontent.com/17510033/41954219-cf019e58-79f7-11e8-9b98-db242e9ea040.png)
 
> Also I am assuming you are using the latest dev/6.0.0 branch

Yes

**Comment by sudar** [comment]
Okay, looks like there was a mis-match in npm version.

I have fixed all the issues except one which is because of a dependency.

Since we are using those scripts only in dev, I think we should be fine.

Closing this for now, but I will keep an eye on it.
