### ISSUE TITLE
Accessibility Suggestion: Add a note on selecting multiple categories (Cmd/Ctrl + Click)

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#342]
![image](https://user-images.githubusercontent.com/17510033/41831603-9952263a-7865-11e8-864e-49b0460f9f98.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

Do you want to handle this after your testing?

You can use the tooltip helper that we already have.

**Comment by mariadanieldeepak** [comment]
@sudar,

This is now handled using Select2. So this issue requires no action to be taken.

![image](https://user-images.githubusercontent.com/17510033/43086778-ce5f652e-8ebb-11e8-8f9a-a25196f55ee0.png)
