### ISSUE TITLE
[Delete Posts By Taxonomy] Missing Test cases

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#345]
@esudalaimadan 

Check if any of the below tests are not present. If not present add them.

Also split the data provider into multiple data providers.

The following test cases are missing.

### Group
- [x] Test deleting Posts associated with built-in taxonomies from one taxonomy term and restrict to posts older than x days by moving to Trash
- [x] Test deleting Posts associated with built-in taxonomies from multiple taxonomy terms and restrict to posts withinn x days by moving to Trash
- [x] Test deleting Posts associated with built-in taxonomies from one taxonomy term and restrict to posts older than x days by deleting permanently
- [x] Test deleting Posts associated with built-in taxonomies from multiple taxonomy terms and restrict to posts withinn x days by deleting permanently
- [x] Test deleting Posts associated with custom taxonomies from one taxonomy term and restrict to posts older than x days by moving to Trash
- [x] Test deleting Posts associated with custom taxonomies from multiple taxonomy terms and restrict to posts within x days by moving to Trash
- [x] Test deleting Posts associated with custom taxonomies from one taxonomy term and restrict to posts older than x days by deleting permanently
- [x] Test deleting Posts associated with custom taxonomies from multiple taxonomy terms and restrict to posts within x days by deleting permanently

### Group
- [x] Test deleting Posts associated with built-in taxonomies from one taxonomy term by moving to Trash
- [x] Test deleting Posts associated with built-in taxonomies from multiple taxonomy terms by deleting permanently
- [x] Test deleting Posts associated with custom taxonomies from one taxonomy term by moving to Trash
- [x] Test deleting Posts associated with custom taxonomies from multiple taxonomy terms by deleting permanently

### Group
- [x] Test deleting Posts associated with built-in taxonomies from one taxonomy term in batches by moving to Trash
- [x] Test deleting Posts associated with built-in taxonomies from multiple taxonomy in batches by moving to Trash
- [x] Test deleting Posts associated with built-in taxonomies from one taxonomy term in batches by deleting permanently
- [x] Test deleting Posts associated with built-in taxonomies from multiple taxonomy in batches by deleting permanently
- [x] Test deleting Posts associated with custom taxonomies from one taxonomy term in batches by moving to Trash
- [x] Test deleting Posts associated with custom taxonomies from multiple taxonomy terms in batches by moving to Trash
- [x] Test deleting Posts associated with custom taxonomies from one taxonomy term in batches by deleting permanently
- [x] Test deleting Posts associated with custom taxonomies from multiple taxonomy terms in batches by deleting permanently

**Comment by mariadanieldeepak** [comment]
@rajanit2000,

The missing test cases have been identified and listed above. Please do let us know in case you have any questions on the identified test cases.

**Comment by esudalaimadan** [comment]
Added test cases specified in the spreadsheet https://docs.google.com/spreadsheets/d/1ZXGhhvgDMLhnl1EubaFBWwWHbkNb_x4KoCI95bhmOE4/edit#gid=0.
