### ISSUE TITLE
Accessibility Suggestion: [Delete Posts By Tag]

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#346]
Showing Users tags with 0 posts doesn't help the User

![image](https://user-images.githubusercontent.com/17510033/41886063-540a5f58-7918-11e8-9202-3fbe2d166100.png)

Also, it is not with our system. Because in Posts by Post Type we only show Post status when posts count > 0

![image](https://user-images.githubusercontent.com/17510033/41886098-86f25088-7918-11e8-9d18-ad5a1c676a25.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

Verify and close it if nothing needs to be done.

**Comment by mariadanieldeepak** [comment]
@sudar,

Closing this as Select2 library works great.

![image](https://user-images.githubusercontent.com/17510033/41951914-f27a01f2-79ea-11e8-9006-eceb472d7385.png)
