### ISSUE TITLE
[Delete Posts by Post Type]: No Test cases exists

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#347]
Write test cases for Delete Posts By Post Type

**Comment by sudar** [comment]
The tests are written as part of #250 

Verify if all the needed tests are present and close it.

**Comment by mariadanieldeepak** [comment]
@rajanit2000,

Assign this back to me once you're done with #250.

**Comment by sudar** [comment]
@mariadanieldeepak 

#250 is merged

**Comment by mariadanieldeepak** [comment]
@sudar Alright, thank you.
