### ISSUE TITLE
Delete Post Revisions: Add Tests

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#353]
Blocked by #178

**Comment by sudar** [comment]
@mariadanieldeepak 

Post revisions have test cases now.

Check the latest `dev/6.0.0` branch.

**Comment by mariadanieldeepak** [comment]
@rajanit2000,
 
It appears to me that you don't have to set the following options unless you plan to use it.

https://github.com/sudar/bulk-delete/blob/dev/6.0.0/tests/wp-unit/include/Core/Posts/Modules/DeletePostsByRevisionModuleTest.php#L56-L58

Those options are set to default here.

https://github.com/sudar/bulk-delete/blob/dev/6.0.0/include/Core/Posts/PostsModule.php

One thing I noticed is that, `revisions` are permanently deleted, and in that case setting `force_delete` to `false` could mislead.

@sudar - Kindly correct me if I'm wrong.

**Comment by sudar** [comment]
@mariadanieldeepak 

What you are saying makes sense.

Add instructions on what needs to be changed so that @rajanit2000 can make those changes.

**Comment by mariadanieldeepak** [comment]
@rajanit2000,

Kindly watch this video for specific instructions - https://bulkwp.slack.com/archives/C030FQZKZ/p1530242443000172

And let me know in case you have any questions.

**Comment by mariadanieldeepak** [comment]
@rajanit2000,

Kindly let me know if you have an update for me.

**Comment by rajanit2000** [comment]
Status: Not yet started

**Comment by rajanit2000** [comment]
Waiting for review
https://github.com/sudar/bulk-delete/pull/403
