### ISSUE TITLE
Delete Posts by Post status - Custom Post status - Add Tests: Review Feedback

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#358]
This issue is part of #189.

The following are the review comments.
https://github.com/sudar/bulk-delete/issues/189#issuecomment-400549822

@rajanit2000 Kindly assign this back to @sudar once you're done with this issue.

**Comment by rajanit2000** [comment]
Status: Not yet started

**Comment by rajanit2000** [comment]
Missed by 17th July Sprint
Reason: Wrong estimation for Car Plugin
