### ISSUE TITLE
Unable to run PHPUnit after getting latest from Repo

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#359]
@sudar,

I'm unable to run PHPUnit after pulling the latest changes from Repo.

![image](https://user-images.githubusercontent.com/17510033/42014301-387338f2-7abf-11e8-9266-f28808ee4ec7.png)

I tried to remove `vendor/` and then tried `composer install`, but that didn't help much.

**Comment by sudar** [comment]
@mariadanieldeepak 

You are not using the phpunit.xml file.

Run the following commands instead of the ones you are using.

- `npm run unit` -> To run only wp unit tests
- `npm run mock` -> To run only wp mock tests
- `npm run test` -> To run both tests

**Comment by mariadanieldeepak** [comment]
@sudar,

Closing this issue as the above commands work.
