### ISSUE TITLE
Delete users by post count, counts only "post" post type

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#36]
This is because `count_user_posts` only supports "post" post type. This has to be extended to provide support for other custom post types as well.

Reported at http://wordpress.org/support/topic/respect-post-types-1?replies=2#post-4919478

**Comment by mariadanieldeepak** [comment]
## Verification:

**Creating a test user for whom the posts count is 0.**

![image](https://user-images.githubusercontent.com/17510033/31979730-d6520808-b965-11e7-9cae-1e8f21b90cd4.png)


**Creating a custom post type by logging in as the test user.**

![image](https://user-images.githubusercontent.com/17510033/31979737-e2d5b99e-b965-11e7-9ce5-676601f2a9b2.png)


**Selecting the appropriate delete options (Note the cursor) to delete the user with no posts.**

![image](https://user-images.githubusercontent.com/17510033/31979742-ec558bde-b965-11e7-8567-85c9de942d07.png)

![image](https://user-images.githubusercontent.com/17510033/31979746-f02745d6-b965-11e7-955b-5d19d159a78c.png)


**No Post should be deleted as the User has authored one CPT.**

![image](https://user-images.githubusercontent.com/17510033/31979760-fc33f982-b965-11e7-825b-9aea25ab701a.png)

**Comment by mariadanieldeepak** [comment]
Note: The copy on the filtering options has been changed after I took the above screenshot.

![image](https://user-images.githubusercontent.com/17510033/31979856-83197738-b966-11e7-9b5c-35ccf0693f8b.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

Yeah, right now it considers only built-in post types. The requirement is to make this filter support additional CPT's as well.

**Comment by mariadanieldeepak** [comment]
@sudar,

This issue is fixed and the PR containing the fix is here - https://github.com/sudar/bulk-delete/pull/142

Did I miss anything here?

**Comment by sudar** [comment]
@mariadanieldeepak 

Can you create a PR by branching off from dev/5.6 branch? I am not able to see the code change for this.

**Comment by mariadanieldeepak** [comment]
@sudar,

My changes pertaining to this issue, is already merged into `dev/5.6` and I'm not sure how that happened.

But the following are the changes.

https://github.com/sudar/bulk-delete/commit/273914be1e01db83b648356bbb35dcb96e99437b#diff-53156dc104c7e0150399b31e8b80fea2R66

**Comment by mariadanieldeepak** [comment]
@sudar,

Let me get that fixed myself.

**Comment by mariadanieldeepak** [comment]
@sudar - Sent a PR by cherry-picking the direct commits made on `dev/5.6` on to a new branch. Kindly review the PR and close the issue.
