### ISSUE TITLE
[Delete Posts by Post Type]: Review

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#361]
Blocks #303

**Comment by mariadanieldeepak** [comment]
@sudar, @rajanit2000,

The issue has been explained in this [video](https://bulkwp.slack.com/archives/G6LDSN6R2/p1530590654000051). Also, I took time to debug and fixed the issue.

**Comment by mariadanieldeepak** [comment]
@sudar,

PR sent and assigning this to you for review.

**Comment by sudar** [comment]
@mariadanieldeepak 

Closing this, since this got fixed as part of #365 

Re-open it if needed.
