### ISSUE TITLE
Add null check or make sure $options['selected_tags'] is array

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#367]
Blocks #303 

There is a possibility that the `$options['selected_tags']` could be `null` in the following line.

https://github.com/sudar/bulk-delete/blob/dev/6.0.0/include/Core/Posts/Modules/DeletePostsByTagModule.php#L88

and that is because of the following line.

https://github.com/sudar/bulk-delete/blob/dev/6.0.0/include/Core/Posts/Modules/DeletePostsByTagModule.php#L79

**Comment by sudar** [comment]
@mariadanieldeepak 

Good catch. Fixed in #381
