### ISSUE TITLE
Fix the Function name as per the implementation

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#368]
Blocks #303 

The function name says that the posts are `deleted`, but it is actually `trashed`.

**Function name**

https://github.com/sudar/bulk-delete/blob/65fcd7500dd647168deaafbf81d09e766c60b19e/tests/wp-unit/include/Core/Pages/Modules/DeletePagesByStatusModuleTest.php#L105

**Implementation**

https://github.com/sudar/bulk-delete/blob/65fcd7500dd647168deaafbf81d09e766c60b19e/tests/wp-unit/include/Core/Pages/Modules/DeletePagesByStatusModuleTest.php#L128

Kindly fix this.

**Comment by rajanit2000** [comment]
Its simple issue, I plan to complete after close all pending tickets ( #403, #395, #382, #332 )
Missed current sprint (17th July), 
It will be complete (next sprint)
Reason for the delay: Car plugin wrong estimation
