### ISSUE TITLE
[Page By Status] Missing Tests for Pages by Status

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#369]
The following test is missing it counterpart (i.e. `test_that_pages_that_are_older_than_x_days_can_be_trashed`)

https://github.com/sudar/bulk-delete/blob/65fcd7500dd647168deaafbf81d09e766c60b19e/tests/wp-unit/include/Core/Pages/Modules/DeletePagesByStatusModuleTest.php#L105

**Related**
https://github.com/sudar/bulk-delete/issues/368

**Comment by sudar** [comment]
@mariadanieldeepak

Let's manually test this feature for v6.0.0 and add the tests in v6.1.0

If you agree, then remove the blocks tag on this.
