### ISSUE TITLE
[Page by Status] Function name & `force_delete` contradicts

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#372]
Blocks #303 

The function name and the `force_delete` flag contradicts.

https://github.com/sudar/bulk-delete/blob/65fcd7500dd647168deaafbf81d09e766c60b19e/tests/wp-unit/include/Core/Pages/Modules/DeletePagesByStatusModuleTest.php#L227

**Comment by rajanit2000** [comment]
Its simple issue, I plan to complete after close all pending tickets ( #403, #395, #382, #332 )
Missed current sprint (17th July), 
It will be complete (next sprint)
Reason for the delay: Car plugin wrong estimation

**Comment by sudar** [comment]
@mariadanieldeepak 

Closing this as invalid, since the function name is correct.
