### ISSUE TITLE
Suggestion: Add a note saying that Admins won't be deleted when deleting Users by User Meta

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#377]
![image](https://user-images.githubusercontent.com/17510033/42411035-2ba2d5f6-8212-11e8-8038-472199d52804.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

That's not correct.

Admin users (even the currently logged-in user) will be deleted if the user meta matches.

**Comment by mariadanieldeepak** [comment]
@sudar,

I'll make a test and report here. Adding it to the queue.

**Comment by mariadanieldeepak** [comment]
@sudar,

I verified that the module deletes even Admin who fulfil the criteria. The only thing is after deletion, WP shows the count of users deleted on the admin screen of the deleted user. Once the User navigates to any other page, then WP redirects to the login screen.

To my knowledge the above action is expected. Hence closing this issue.
