### ISSUE TITLE
Suggestion: Consider adding a note under By User Meta module when looking to filter User Role

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#379]
@sudar,

In the "By User Meta" module, only the meta key can be selected and not the User role. Consider adding a note so Users who want to filter User role, can use the "Bulk Delete User Meta module" under `Bulk Delete Meta Fields` menu.

**Comment by sudar** [comment]
@mariadanieldeepak 

But there is a difference right?

`Delete User Meta` module allows you to delete user meta, where as `Delete Users by User Meta` module allows you to delete users.

**Comment by mariadanieldeepak** [comment]
> But there is a difference right?

Apologies, I was confused. Both are completely different.
