### ISSUE TITLE
Question on "no_posts_post_types" type

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#380]
Shouldn't the following value be an array?

https://github.com/sudar/bulk-delete/blob/7ea4f4ef3e877f726664e1d79b74c56caf0e89ee/tests/wp-unit/include/Core/Users/Modules/DeleteUsersByUserMetaModuleTest.php#L161

**Comment by sudar** [comment]
@mariadanieldeepak 

Yes, you are correct. Good catch.

## Resolution

Change `no_posts_post_types` to use array instead of string. (ie) use `array( 'post' )`
