### ISSUE TITLE
[Users by Meta] Add tests for all comparison operators

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#383]
Requires #375 
Requires #376

**Comment by mariadanieldeepak** [comment]
Status: Yet to begin

**Comment by mariadanieldeepak** [comment]
Status: This is in-progress and wouldn't be completed on this sprint.
Reason: Issue #303 occupied additional time.

**Comment by mariadanieldeepak** [comment]
Status: In progress
Reason: Working on review feedbacks

**Comment by mariadanieldeepak** [comment]
@sudar, 

I've completed the test cases and I'm so glad about the results.

Here is the before

![image](https://user-images.githubusercontent.com/17510033/43622959-770b4f2e-96fc-11e8-988d-873aec1ec850.png)

and here is the after results.

![image](https://user-images.githubusercontent.com/17510033/43622963-7d2891f0-96fc-11e8-9fcc-69b3a2340426.png)

This is now ready for your review.

**Comment by sudar** [comment]
@mariadanieldeepak 

Awesome.

There were supposed to be some tests that will fail right? The comparison ones that we have not added yet?

**Comment by mariadanieldeepak** [comment]
@sudar,

> There were supposed to be some tests that will fail right? The comparison ones that we have not added yet?

Yeap, I figured out why it failed and I fixed them. The failing test cases were related to [this](https://github.com/sudar/bulk-delete/issues/451#issuecomment-410134761) issue.
