### ISSUE TITLE
[Bulk Delete Post Meta] Add tests to cover post meta field settings

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#387]
Part of #303 

![image](https://user-images.githubusercontent.com/17510033/42546256-3e20a77e-84da-11e8-9c74-4f24bc28e169.png)

**Comment by mariadanieldeepak** [comment]
@sudar,

This issue's test cases must be added to add-ons. Is there an example on any of the add-ons that I can follow?

**Comment by sudar** [comment]
@mariadanieldeepak 

As of now no. Let's bump this up to next milestone.

Does this block any of your work?

**Comment by mariadanieldeepak** [comment]
@sudar,

This issue warrants tests cases to be written for the add-ons. The base plugin test cases are already there, but I have to fix the coding standards and naming conventions.

**Comment by mariadanieldeepak** [comment]
@sudar,

The Base plugin's test cases have been standardised and the respective PR is #444. Kindly review the same.
