### ISSUE TITLE
[Bulk Delete Post Meta] Deletion bug

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#388]
Blocks #303 

**Steps to replicate**

01. Pull latest from `dev/6.0.0` branch

02. Add Post meta to any post of type `post`

![image](https://user-images.githubusercontent.com/17510033/42546670-f928aba6-84db-11e8-9239-c17b3f0c5e2a.png)

03. Try deleting the Post meta by specifying the exact meta key that you've added in the above step.

![image](https://user-images.githubusercontent.com/17510033/42546741-4b70f684-84dc-11e8-855a-08f878075158.png)

04. List Post meta to verify if the deleted value exists. In this case, the meta exists.

![image](https://user-images.githubusercontent.com/17510033/42546933-468428e8-84dd-11e8-9225-d533ea8422fe.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

This is fixed.

Feel free to re-open it if the issue is still present.
