### ISSUE TITLE
[Delete Posts By Title] Suggestion: Add option for case sensitive search

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#390]
Identified as part of #303 

Currently the following module works great. I've a suggestion to add option to Delete posts by title by using a case sensitive title match.

![image](https://user-images.githubusercontent.com/17510033/42548225-c2c5e828-84e3-11e8-8e14-a19d9beaa5ff.png)

**Comment by sudar** [comment]
Good suggestion. Moving this to add-on repo for implementation.
