### ISSUE TITLE
[Bulk Delete User Meta] Not deleting User meta as expected

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#396]
Blocks #303 
Identified as part of #389 

**Problem**

User meta wasn't deleted as expected.

**Data setup**

![image](https://user-images.githubusercontent.com/17510033/42669635-18a6c528-8674-11e8-80d7-7c623f0e3c2d.png)

**Module options**

![image](https://user-images.githubusercontent.com/17510033/42669664-4cf0231a-8674-11e8-985a-42f5216f4375.png)

**Output**

![image](https://user-images.githubusercontent.com/17510033/42669682-70b99650-8674-11e8-8756-3714b2548188.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

This is fixed.

Feel free to re-open it if the issue is still present.
