### ISSUE TITLE
[Bulk Delete Posts By Users] Couldn't find the module

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#398]
Though I have the add-on activated, yet I couldn't find the module under `Bulk WP` &rarr; `Bulk Delete Posts`

![image](https://user-images.githubusercontent.com/17510033/42670093-91844b80-8676-11e8-9517-1e0b70e67a5d.png)

![image](https://user-images.githubusercontent.com/17510033/42670109-9f4cd778-8676-11e8-8b67-58a30b0e610a.png)

Am I looking at the wrong place? Kindly advise.

**Comment by sudar** [comment]
@mariadanieldeepak 

This issue is fixed now.

Feel free to re-open it if you face the issue again.
