### ISSUE TITLE
[Suggesstion] Make Scheduling much easier for Users

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#409]
Identified as part of #303 

Currently the time shows up as 0:00:00. WordPress usually stores time in local time zone as well as in GMT.

Display the current time in one of the above timezones and that way it will be come easier for Users to set the time relatively. Another idea is to set the schedular to current time so it doesn't always show up `0:00:00`

![image](https://user-images.githubusercontent.com/17510033/42793571-6627b060-8998-11e8-973e-b3ff99833404.png)

**Comment by mariadanieldeepak** [comment]
@sudar,

Looks like `Now` button is just there ;) You're brilliant.

**Comment by sudar** [comment]
@mariadanieldeepak 

Ha ha. Yeah I faced that issue when I was initially testing the scheduler half a decade ago and added the `Now` button :)

I am closing it now since nothing is needed. Feel free to open it if needed.
