### ISSUE TITLE
Suggestion: Introduce "Exclude User ID" filter

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#441]
We have good amount of filters on Bulk Delete Users. I think introducing "Exclude User IDs" filter will make sense.

**Comment by sudar** [comment]
I am also thinking of adding a 'exclude currently logged-in user' filter as well.

**Comment by sudar** [comment]
Closing this since we are already excluding the currently logged-in user from getting deleted.
