### ISSUE TITLE
Suggesstion: Adopt linting using ESLint

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#442]
A good samaritan has already done the ground work.

https://webdevstudios.com/2017/04/06/lint-code-like-boss/

**Comment by sudar** [comment]
ESLint is good if we have lot of ES6 code.

Right now what we have is mostly pre-ES6 code and also the current setup works for us.

I am going to close this for now, but we can revisit once we start having lot of JavaScripts files.
