### ISSUE TITLE
Starts with and Ends with operators not deleting Users as expected

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#451]
![image](https://user-images.githubusercontent.com/17510033/43369146-679a4dde-9386-11e8-901c-1b66e9978b2a.png)

Identified as part of #383 
Blocks #303

**Comment by sudar** [comment]
@mariadanieldeepak 

I just tried and it seems to be deleting users properly.

Can you give me the scenario in which this failing?

**Comment by mariadanieldeepak** [comment]
@sudar,

I was writing test cases for Users By Meta module and found that the Starts with and Ends with conditions weren't giving the expected results.

By taking a quick look I figured out that the values used in UI and in the code doesn't match. The issue could possibly be because of this. 

![image](https://user-images.githubusercontent.com/17510033/43593528-9cef090e-9695-11e8-9fc3-14deff42cd8b.png)

![image](https://user-images.githubusercontent.com/17510033/43593509-924639aa-9695-11e8-8a3a-f061b2c65c22.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

Check line number 103 in the screenshot :)

**Comment by mariadanieldeepak** [comment]
@sudar,

I figured out what went wrong. There is nothing wrong with the module code.
