### ISSUE TITLE
Delete Comment Meta Operators restriction 

### ISSUE THREAD

**Issue by rajanit2000** [sudar/bulk-delete#460]
![screenshot](https://user-images.githubusercontent.com/2988033/43495954-52c55db2-9558-11e8-9cae-64de03594fce.png)

Need to switch the position of Meta operator and Meta type
Once user choose meta type (ie: 'CHAR') only shows possible meta operators (ie: =, !=, LIKE and NOT LIKE)

@sudar please close this ticket if it is does not make sence

**Comment by sudar** [comment]
@esudalaimadan 

Let's implement this.
