### ISSUE TITLE
DeleteTermsByNameModuleTest fails for the 'not_equal_to' and 'equal_to' datasets

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/bulk-delete#497]
Blocks #478 

There were 4 failures:

1) BulkWP\BulkDelete\Core\Terms\Modules\DeleteTermsByNameModuleTest::test_that_terms_can_be_deleted_by_name_using_various_filters with data set #0 (array('post', 'post_tag', array('Term A', 'Term B', 'Term C', 'term A')), array('Term A', 'equal_to'), 1, array('Term B', 'Term C', 'term A'))
Failed asserting that null is not null.
-------------------------------------------------------------------------------
2) BulkWP\BulkDelete\Core\Terms\Modules\DeleteTermsByNameModuleTest::test_that_terms_can_be_deleted_by_name_using_various_filters with data set #4 (array('post', 'post_tag', array('Term A', 'Term B', 'Term C', 'term A')), array('Term A', 'not_equal_to'), 3, array('Term A'))
Failed asserting that 2 matches expected 3.
--------------------------------------------------------------------------------
3) BulkWP\BulkDelete\Core\Terms\Modules\DeleteTermsByNameModuleTest::test_that_terms_can_be_deleted_by_name_using_various_filters with data set #6 (array('post', 'custom_taxonomy', array('Term A', 'Term sample B', 'Term Sample C')), array('Term sample C', 'not_equal_to'), 3, array())
Failed asserting that 2 matches expected 3.
----------------------------------------------------------------------------------
4) BulkWP\BulkDelete\Core\Terms\Modules\DeleteTermsByNameModuleTest::test_that_terms_can_be_deleted_by_name_using_various_filters with data set #7 (array('post', 'custom_taxonomy', array('Term A', 'Term sample B', 'Term Sample C')), array('Term sample', 'not_equal_to'), 0, array('Term A', 'Term sample B', 'Term Sample C'))
Failed asserting that 3 matches expected 0.

**Comment by rajanit2000** [comment]
1. We could not insert terms with the same name (It's not case sensitive). 
https://www.evernote.com/shard/s744/u/0/sh/4d270d00-353e-40fd-a0bb-0d837262f80a/454edd6b63bd16a7555fa995a86135e2

If we pass `array('Term A', 'Term B', 'Term C', 'term A')` Just the first three terms should be added

**Comment by rajanit2000** [comment]
@sudar I have to fix this issue #502

**Comment by sudar** [comment]
@rajanit2000 

Terms are not case sensitive in WordPress.

If you pass `Term A` and `term A`, then it should create two terms.
