### ISSUE TITLE
Deleting Users - Batches won't work with post count filter or last login date filter

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/bulk-delete#503]
limit_to filter with other filter combinations fail as the current logic first takes the limit_to no.of rows and then applies other selected filter(s).
Expected Logic: Apply selected filter(s) and for the resulting rows apply limit_to filter.

14 tests are failing due to the above issue in https://github.com/sudar/bulk-delete/blob/486-fix/user-module-test-using-all-filters/tests/wp-unit/include/Core/Users/Modules/DeleteUsersByUserMetaModuleTest.php
Make sure all the tests pass once thementioned issue is fixed.

Blocks #486 and PR: #492

**Comment by esudalaimadan** [comment]
Blocks #492

**Comment by sudar** [comment]
@esudalaimadan 

I have fixed the logic that caused `limit_to` to fail.

But now 12 test cases are still failing. I think this is happening because of some other problem. Can you check it again?
