### ISSUE TITLE
Add a note about cron schedules and link to doc

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#505]
The doc will be available after https://github.com/sudar/bulk-wp-site/issues/51

---

## Attached PR(s)
https://github.com/sudar/bulk-delete/pull/514

**Comment by mariadanieldeepak** [comment]
@sudar,

Here is a preview of the added Tooltip. The development is complete and is ready for your review.

![image](https://user-images.githubusercontent.com/17510033/45432734-2ed18e80-b6c8-11e8-8c19-1946dd7aa219.png)
