### ISSUE TITLE
Enhance Data Type and Operator Dropdowns in Delete Meta Module

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/bulk-delete#516]
- [x] Make Operator Dropdown to show relevant operators based on selected DataType.
- [x] Make Operator Dropdown and DataType Dropdown generic which can be used across post,comment and user meta modules.

## Data Type dropdown

The following values will be present in the data type dropdown

- Number
- Character
- Date

## Operators

Data Type | Operator
------------ | -------------
Number | '=', '!=', '>', '>=', '<', '<=', 'IN', 'NOT IN', 'BETWEEN', 'NOT BETWEEN'
Character | '=', '!=', 'LIKE', 'NOT LIKE', 'IN', 'NOT IN',
Date | '=', '!=', '>', '>=', '<', '<=', 'IN', 'NOT IN', 'BETWEEN', 'NOT BETWEEN'
All | 'EXISTS' and 'NOT EXISTS'.

## Date

For date operator we should support Date format as well. Refer to Bulk Delete Posts by Custom Field add-on for code

## EXISTS and NOT EXISTS

For exits and not exists we should hide the value textbox

## 'IN', 'NOT IN', 'BETWEEN', 'NOT BETWEEN'

For these operators we will ask the user to enter multiple values seperate by comma.

**Comment by esudalaimadan** [comment]
**Known Issues:**

1. NOT EXISTS operator is not working as expected.
2. When user specifies Date Format, it is not working properly.
3. DatePicker is not applying css properly.

**Not yet Implemented**
1) BETWEEN, NOT BETWEEN operators.
2) IN and NOT IN operators.

**Comment by sudar** [comment]
@esudalaimadan 

Let's revisit this again and get it to closure.

Currently the PR #564 is having a conflict. Merge the latest `dev/6.1.0` branch and resolve the conflict.

After that for this sprint, just identify the list of pending items and then add them as comment.

**Comment by esudalaimadan** [comment]
**Finished Items**:

1. Generic JS which can be used for all meta modules( i.e., PostMeta, CommentMeta and UserMeta).
2. Comment Meta Module alone, now uses the enhanced datatype dropdown.
3. Comment Meta Module works for all data types.(Except for NOT EXISTS  and Date Format specification)

**Pending Items:**
**Backend problems:**(Implemented but has issues)

1. NOT EXISTS operator is not working as expected.(Test is available).
2. When user specifies Date Format, it is not working properly. (Test is available). - Query overrider has to be changed to support WP_Meta_Query.

**Frontend Problems:**(Not yet implemented)

- BETWEEN, NOT BETWEEN, IN and NOT IN for DATE type.

Tests available for following data type operator  combination
![image](https://user-images.githubusercontent.com/38071735/62106276-7b16c480-b2c2-11e9-9402-c47a19a8ca7f.png)





**Short term goals:**
Has to be extended for PostMeta and UserMeta modules.
Has to be extended for DeletePostsByCustomField Addon.

**Comment by esudalaimadan** [comment]
@sudar I have resolved the conflicts and commited changes in the following branch.
516-fix/enhance-data-type-and-operator-dropdowns

**Comment by esudalaimadan** [comment]
**Pending Items:**
1. NOT EXISTS operator is not working as expected.(Test is available).
2. Query overrider has to be made generic.( parse_comment_query is used currently for comment meta )
3. BETWEEN, NOT BETWEEN, IN and NOT IN operators for DATE type is not implemented.
4. Has to be extended for PostMeta and UserMeta modules.
5. Has to be extended for DeletePostsByCustomField Addon.

**Finished Items**:
1. Generic JS which can be used for all meta modules( i.e., PostMeta, CommentMeta and UserMeta).
2. Comment Meta Module alone, now uses the enhanced datatype dropdown.
3. Comment Meta Module works for all data types.(Except for NOT EXISTS  operator)

Tests available for following data type operator  combination
![image](https://user-images.githubusercontent.com/38071735/70122447-a6f1ee80-1696-11ea-8ce4-c5539e14a815.png)

**Comment by sudar** [comment]
@esudalaimadan 

Regarding the pending items.

> NOT EXISTS operator is not working as expected.(Test is available).

We need to fix it before v6.1.0 release.

> Query overrider has to be made generic.( parse_comment_query is used currently for comment meta )

We need to fix it before v6.1.0 release.

> BETWEEN, NOT BETWEEN, IN and NOT IN operators for DATE type is not implemented.

This can wait. I have created #695 to handle this later.

> Has to be extended for PostMeta and UserMeta modules.

This can wait. I have created #696 and #697 to handle this later.

> Has to be extended for DeletePostsByCustomField Addon.

This can wait as well. Create https://github.com/sudar/bulk-delete-posts-by-custom-field/issues/21 to handle this.

**Comment by sudar** [comment]
Created the following issues to handle the pending items.

#700 
#701
