### ISSUE TITLE
Ability to delete posts based on number of comments

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#52]
@esudalaimadan 

Use the following content for the module.

- Title => Delete Posts based on the number of comments
- Select the comment settings based on which posts should be deleted
- Delete posts that have comments {dropdown} {textbox}

**Comment by esudalaimadan** [comment]
@sudar ,
1) Posts with private and draft status should be deleted or not?
2) Need your help in displaying the module in the right place.  Currently, it is getting displayed at the bottom of the page.

**Comment by sudar** [comment]
@esudalaimadan 

This module appears in the correct place for me.

<img width="1440" alt="screenshot 2018-11-01 22 18 08" src="https://user-images.githubusercontent.com/103148/47866233-30941480-de24-11e8-9938-a2a107eaf1b8.png">
