### ISSUE TITLE
Bulk Delete Comment Meta: Show Docs link to add Cron schedules since Scheduler is always enabled

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#531]
![image](https://user-images.githubusercontent.com/17510033/45938324-90f29380-bfe6-11e8-8496-c2c9c677a7a4.png)

This is part of https://github.com/sudar/bulk-delete/pull/514#issuecomment-423875126

**Comment by sudar** [comment]
Closing this since this is also fixed now.
