### ISSUE TITLE
DeleteUsersModule Tests

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/bulk-delete#540]
Figure out an architecture so that dataset and test duplication is avoided.
1) Dataset sharing
2) Generic tests which will minimize the test writing effort in newly added modules.

**Comment by sudar** [comment]
Check the tests that I have written for the `UsersModule`. Especially the ones for testing that reassign user works.

**Comment by esudalaimadan** [comment]
On Hold. Unable to run tests due to phpunit incompatibility issue.

**Comment by sudar** [comment]
I have fixed the PHPUnit incompatibility issue.

Do the following steps.

1) Delete `vendor` directory
2) Get latest code from `dev/6.0.0`
3) run `composer install` command
4) run `npm run unit` to run the tests

Let me know if you are still facing any issues here.

**Comment by esudalaimadan** [comment]
@sudar It works now.
