### ISSUE TITLE
Delete users without deleting content

### ISSUE THREAD

**Issue by concentrateddon** [sudar/bulk-delete#550]
Scanning the code, it seems you're using the normal wp_delete_user() to accomplish user deletion, but not passing the parameter to re-attribute the content to someone else, which, I understand, will cause that user's content to also be deleted...?

Are there plans to allow for bulk user deletion and either (a) attribute their content to a single specified user or (b) attribute their content to "Anonymous?"

**Comment by sudar** [comment]
@concentrateddon 

Thanks for raising this.

So far we didn't provide any option to re-assign the content. We are adding this to the list of things that we want to get done for our next release.

**Comment by sudar** [comment]
@concentrateddon 

We have just released v6.0.0 of the plugin with the ability to map content of users who are getting deleted to other users.

Please try out the feature and let us know if you have any feedback or questions.
