### ISSUE TITLE
JavaScript error in Safari

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#555]
The latest `dev/6.0.0` is generating an JavaScript error in Safari Mac

---

## Attached PR(s)
https://github.com/sudar/bulk-delete/pull/563

**Comment by sudar** [comment]
@mariadanieldeepak 

Can you just try it once and confirm whether you are getting the error or not?

**Comment by mariadanieldeepak** [comment]
@sudar,

Did you find JS errors on any specific pages or across all Bulk Delete pages?

I found no errors on the following pages:

- http://local.wordpress.test/wp-admin/admin.php?page=bulk-delete-posts
- http://local.wordpress.test/wp-admin/admin.php?page=bulk-delete-pages
- http://local.wordpress.test/wp-admin/admin.php?page=bulk-delete-users
- http://local.wordpress.test/wp-admin/admin.php?page=bulk-delete-metas
- http://local.wordpress.test/wp-admin/admin.php?page=bulk-delete-terms
- http://local.wordpress.test/wp-admin/admin.php?page=bulk-delete-misc
- http://local.wordpress.test/wp-admin/admin.php?page=bulk-delete-attachment
- http://local.wordpress.test/wp-admin/admin.php?page=bulk-delete-cron
- http://local.wordpress.test/wp-admin/admin.php?page=bulk-delete-addon
- http://local.wordpress.test/wp-admin/admin.php?page=bulk-delete-info

I tested the above pages on the following Safari version.

![image](https://user-images.githubusercontent.com/17510033/47765382-b5314680-dcef-11e8-8e99-27c365fb24c4.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

See if you are able to see any error with the latest dev version of [Bulk Delete Attachments add-on](https://github.com/sudar/bulk-delete-attachments/).

**Comment by mariadanieldeepak** [comment]
@sudar,

I don't see any error w/ the latest from master on both Bulk Delete and the Bulk Delete Attachment add-on.

**I've one item in the library**

![image](https://user-images.githubusercontent.com/17510033/47976790-4af71800-e0da-11e8-8492-2c73328f1fd3.png)

**My Delete condition**

![image](https://user-images.githubusercontent.com/17510033/47976811-6f52f480-e0da-11e8-920e-518800b2bb9a.png)

**No of attachments deleted**

![image](https://user-images.githubusercontent.com/17510033/47976826-7a0d8980-e0da-11e8-8a52-ff582d5635e4.png)

In none of the screens, I see errors in the Console.

**Comment by sudar** [comment]
@mariadanieldeepak 

Check the following combinations.

Bulk Delete | Bulk Delete Attachment Add-on
-----------|-----------
Master|Master
Master|dev/1.3.0
dev/6.0.0|Master
dev/6.0.0|dev/1.3.0

**Comment by mariadanieldeepak** [comment]
The following are the issues identified while testing with different branches.

- [ ] https://github.com/sudar/bulk-delete/issues/562

**Comment by mariadanieldeepak** [comment]
@sudar,

I captured the following error when testing w/ the following conditions.

Bulk Delete: `dev/6.0.0`
Bulk Delete Attachment Add-on: `master`

![image](https://user-images.githubusercontent.com/17510033/48392931-7d84be80-e733-11e8-80d0-36c78acd34bd.png)

**Comment by mariadanieldeepak** [comment]
@sudar,

I've fixed the above identified JS error. Could you please take over https://github.com/sudar/bulk-delete/issues/555#issuecomment-438142158
