### ISSUE TITLE
Check `dev/6.0.0` branch in WordPress 5.0 beta

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#560]
WordPress 5.0 (which is going to be released sometime around Nov 19th) is making a fundamental change in how edit post screen will be rendered.

We are using lot of Metaboxes for displaying the different modules and there is a possibility that we may have to make some tweaks.

Download the latest beta of WordPress 5.0 from https://wordpress.org/news/2018/11/wordpress-5-0-beta-3/ and run the latest version of `dev/6.0.0` in WordPress 5.0 to see whether everything works properly.

**Comment by esudalaimadan** [comment]
Found a bug and created following issue:
Delete By comments count module JS issue #561
