### ISSUE TITLE
[Delete Posts by Taxonomy] - Show only taxonomies that are associated with a post type

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/bulk-delete#576]
In DeletePostsByCategory and DeletePostsByTaxonomy modules,
1) select post type other than 'post'
**Expected Behaviour:** Category listing should change according to the post type selected.
**Current Behaviour:** Category listing is not changing according to the post type selected.  It always lists built-in categories/taxonomies.
![screenshot from 2018-12-13 12-19-41](https://user-images.githubusercontent.com/38071735/49920909-e053ac00-fed1-11e8-94f0-cf7642a69779.png)

Blocks #523

**Comment by sudar** [comment]
Will be fixed as part of #523
