### ISSUE TITLE
PHP Notice in log

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/bulk-delete#577]
Steps to reproduce:
1) Tail debug.log
2) Select **Bulk Delete Meta Fields** from BulkWP menu.

PHP Notice:  Undefined variable: pro_class in /var/www/html/bulkwp/wp-content/plugins/bulk-delete/include/Core/Base/Mixin/Renderer.php on line 486

**Comment by sudar** [comment]
This is fixed by the commit https://github.com/sudar/bulk-delete/commit/7b67db292b48026989baa79e5e8f4f0629bccee7 and hence closing it.
