### ISSUE TITLE
Delete users who belong to 'no role'

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#579]
Follow these steps to create users who belong to no user role

- Directly insert a user into the wp_users table
- Go to edit user page and then update the user
- Now check the user role for the user

After creating the data set try to see if the 'no role' user role is getting displayed in the 'Delete Users by User Role' Module.

**Comment by esudalaimadan** [comment]
Created the user following the description.
'No Role' is not getting listed in **DeleteUsersByUserRole** Module dropdown.

**Comment by sudar** [comment]
@esudalaimadan 

I have added the code to display users who don't belong to any user role in the `DeleteUsersByUserRole` module.

You need to add the code to delete them.

First try to see if we can retrieve users who don't belong to any user role by the following logic.

```
$user_query_args = array(
'role__not_in' => array( 'list of all roles'), 
);
```

If the above logic doesn't work, then check the `wp{table_prefix}_capabilities` meta field

**Comment by sudar** [comment]
@esudalaimadan 

I have implemented the ability to delete users with no user role. If you are interested in checking out the code, the see this commit - https://github.com/sudar/bulk-delete/commit/b411c241256a81fa9ee53883282a978c1b01164c

**Comment by esudalaimadan** [comment]
Cool 👍

**Comment by esudalaimadan** [comment]
---------- Forwarded message ---------
From: Ezhilarasi S <ezhil.madan@gmail.com>
Date: Sat, 19 Jan 2019 12:39
Subject: Re: [sudar/bulk-delete] Apply a filter to exclude EDD customers
(#585)
To: Sudar Muthu <sudar@sudarmuthu.com>


Sudar, You said there will be more than 1000 users in Edd customers, so we
can not use exclude argument or exclude filter.  If we can have exclude, we
can add it in the build query itself.

Ezhilarasi S.
