### ISSUE TITLE
Suggestion: Implement Autocomplete off on Enter License Key input

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-delete#628]
https://www.w3schools.com/tags/att_input_autocomplete.asp

Currently autocomplete stores the License keys and I think this should be avoided.

**Comment by sudar** [comment]
@mariadanieldeepak 

Any specific reason for this suggestion?

**Comment by sudar** [comment]
Discussed with @mariadanieldeepak and we found that the advantages outweigh disadvantages. Hence closing this as wontfix.
