### ISSUE TITLE
Check if the admin UI works correctly in WordPress 5.3

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#679]
Recently WordPress 5.3 (which is going to be released soon) has made lot of changes to the admin UI CSS - https://make.wordpress.org/core/2019/10/18/noteworthy-admin-css-changes-in-wordpress-5-3/

We need to test to make sure that Bulk Delete is not affected.

@esudalaimadan 

Follow these steps

- Download WordPress 5.3 beta
- Test all the screens of Bulk Delete in WordPress 5.3
- Report any issues

**Comment by esudalaimadan** [comment]
Tested and created tickets for the issues found:
https://github.com/sudar/bulk-delete/issues/680
https://github.com/sudar/bulk-delete/issues/681
https://github.com/sudar/bulk-delete/issues/682
https://github.com/sudar/bulk-delete/issues/683

**Comment by sudar** [comment]
Issues identified will be fixed in individual tickets.
