### ISSUE TITLE
Delete posts by URL doesn’t work in WP 5.3

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#698]
Reported at https://wordpress.org/support/topic/delete-posts-by-url-doesnt-work-in-wp-5-3/#post-12203126

**Comment by esudalaimadan** [comment]
I am not able to reproduce the issue. Details below:
1. I have used Wordpress 5.3.  Installed `Bulk Delete` (Version 6.0.2) from Add Plugins page(which is available to end user).
2. Created custom post type(product) post and able to delete it successfully via DeleteByURL module.

Only thing is Success message is incorrect. It is coming as **Deleted 1 post with post status**

Suggestion:
a) We can ask for the URL customer is trying to delete.
b) What is the Bulk Delete version the customer is using?

**Comment by sudar** [comment]
Closing this, since we are not able to replicate it.
