### ISSUE TITLE
Add help icon to User Modules

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/bulk-delete#716]
Add a help icon in User modules with the following hover message.
Custom post type posts eg. bbPress topics,WooCommerce products etc., will NOT be deleted even if Also Delete Posts option is selected.

**Comment by sudar** [comment]
Use the following message.

"Some custom post types like bbPress topics which have disabled the `delete_with_user` post type attribute will not be deleted. More details".

Link `More details` to this link https://bulkwp.com/docs/deleting-posts-automatically-when-the-post-author-is-deleted
