### ISSUE TITLE
Compatibility with WordPress 5.4

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#726]

**Comment by esudalaimadan** [comment]
Minor css issues with the dropdown height. Dropdown functionality is fine. The following are master branch findings:
![Screenshot from 2020-04-08 12-38-57](https://user-images.githubusercontent.com/38071735/78755724-40a81000-7997-11ea-9326-f02de0802ae4.png)
![Screenshot from 2020-04-08 12-42-46](https://user-images.githubusercontent.com/38071735/78755770-561d3a00-7997-11ea-94de-47e284a826b2.png)
![Screenshot from 2020-04-08 12-42-34](https://user-images.githubusercontent.com/38071735/78755780-5a495780-7997-11ea-97a3-176a2f9ed44d.png)

![Screenshot from 2020-04-08 12-42-34](https://user-images.githubusercontent.com/38071735/78756007-b4e2b380-7997-11ea-8ffd-766dbbf3251c.png)

**Comment by esudalaimadan** [comment]
dev/6.1.0 looks good with 5.4.

**Comment by sudar** [comment]
Closing since `dev/6.1.0` looks good.
