### ISSUE TITLE
Delete Posts by URL module

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#727]
A user complained that they are not able to use full post urls including the domain in this module.

Check if we can give full urls for deletion instead of just the permalink part alone.

**Comment by esudalaimadan** [comment]
Able to delete posts(public and private) with full URLs.

Suggestion:
We can ask the pattern of URLs they are using i.e., failing URLs that they have used.  We may get an idea seeing those failing example URLs.

**Comment by sudar** [comment]
Closing this since we are not able to replicate it.
