### ISSUE TITLE
Enhancements to date filter

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#735]
Right now the date filter only allows the user to choose between posts that are older than xx days or published within the last xx days.

Following are additional features that can be added to this filter

- [x] Ability to select a specific publish date/day using a date selector. For example all posts published on the 11th of January 2019
- [x] Ability to select a range - a start and end date using date selector, so you can pinpoint the publish date range for example 1 until 11th of January 2019.

**Comment by sudar** [comment]
@esudalaimadan 

What is the status of this ticket?

**Comment by esudalaimadan** [comment]
This ticket is completed and available in PR https://github.com/sudar/bulk-delete/pull/750
