### ISSUE TITLE
Fix user id retrieval with emails and exclude key problems

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/bulk-delete#744]
These have been fixed in addon https://github.com/sudar/bulk-delete-users-from-csv/pull/9

**Comment by sudar** [comment]
@esudalaimadan 

I am assuming that we don't have to do anything for this ticket in Bulk Delete. Is that correct?

**Comment by esudalaimadan** [comment]
No, we need to do some changes in dev/6.1.0 and that is why I created this ticket.
