### ISSUE TITLE
Ability to delete all empty posts

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#8]
Might go under a new section "Delete posts by content"

**Comment by mariadanieldeepak** [comment]
@sudar,

Assuming we check the `the_content()` of the posts to filter the posts with empty content, should we give the option to user to filter by post status?

![image](https://user-images.githubusercontent.com/17510033/32207900-0f61d7cc-be25-11e7-9aab-8dc0d82396c6.png)

Or should we go ahead and delete posts with empty content regardless of their `post_status`?

**Comment by sudar** [comment]
@mariadanieldeepak 

I think this can be solved by https://github.com/sudar/bulk-delete/issues/20

**Comment by sudar** [comment]
Will be handled as part of https://github.com/sudar/bulk-delete/issues/20#issuecomment-341908274
