### ISSUE TITLE
Delete user (subscribers) with no post types

### ISSUE THREAD

**Issue by RaquelPatro** [sudar/bulk-delete#91]
Delete users who have not written post types. Serve for many plugins that allow subscribers to write and do not differentiate them from spammers. Like directory plugins.

**Comment by mariadanieldeepak** [comment]
@sudar,

Is this implementation going to be an add-on? 

> Delete users who have not written post types.

Are we intending to delete users who has no content published irrespective of the post types?

**Comment by sudar** [comment]
This needs to be done as a new module under Bulk Delete Users.

The name of the module will be "Delete Users by Content". It will list all the post types (including custom post types). The users can choose the post types and delete users who have not written any post in that post type.

**Comment by mariadanieldeepak** [comment]
Branch: [feature/delete-subscribers-with-no-posts](https://github.com/sudar/bulk-delete/tree/feature/delete-subscribers-with-no-posts)

**Comment by sudar** [comment]
@mariadanieldeepak 

Do we have a PR for this?

**Comment by mariadanieldeepak** [comment]
@sudar,

> Do we have a PR for this?

Work is in-progress. I mentioned the branch name here for convenience.

**Comment by sudar** [comment]
@mariadanieldeepak 

Let's implement it the way you suggested. (ie) add it as a filter instead of creating a different module.

We already have a filter, let's enhance it to display the list of post types if the user chooses this.

Do the implementation in a generic way, so that it can be used across other user modules.

**Comment by sudar** [comment]
@RaquelPatro 

This feature is now available from v5.6.0 of Bulk Delete plugin.
